"""
Django settings for paracelsus project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import json
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9hl)u&#n76-%r=%r@%@fbc9@znxj42bqw&c294-!bov#xm&%&("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "widget_tweaks",
    "haystack",
    "sorl.thumbnail",  # Default thumbnail backend, can be replaced
    "django_tables2",
    "sass_processor",
    "ckeditor",
    "ckeditor_uploader",
    "livereload",
    "django_user_agents",
    "phonenumber_field",
    "import_export",
    "main",
    # "telegram",
    # "qualtest",
]


SITE_ID = 1

HAYSTACK_CONNECTIONS = {
    "default": {
        "ENGINE": "haystack.backends.simple_backend.SimpleEngine",
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
        "LOCATION": "127.0.0.1:11211",
    }
}


"""
OSCAR_PRODUCT_MODEL = 'catalogue.models.CustomProduct'
OSCAR_HIDDEN_FEATURES = ['reviews', 'wishlists']

OSCAR_INITIAL_ORDER_STATUS = 'Pending'
OSCAR_INITIAL_LINE_STATUS = 'Pending'
OSCAR_DEFAULT_CURRENCY = 'RUB'

OSCAR_ORDER_STATUS_PIPELINE = {
    'Pending': ('Being processed', 'Cancelled',),
    'Being processed': ('Processed', 'Cancelled',),
    'Cancelled': (),
}
"""

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "livereload.middleware.LiveReloadScript",
    "django_user_agents.middleware.UserAgentMiddleware",
    # "oscar.apps.basket.middleware.BasketMiddleware",
    # "django.contrib.flatpages.middleware.FlatpageFallbackMiddleware",
]

ROOT_URLCONF = "paracelsus.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.profile",
                # "main.context_processors.remaining",
                # "main.context_processors.glob_csrf",
                # "main.context_processors.metrika",
            ],
        },
    },
]

WSGI_APPLICATION = "paracelsus.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
    # "default": {
    # "ENGINE": "django.db.backends.postgresql_psycopg2",
    # "NAME": "paracelsus_db",
    # "USER": "paracelsus_user",
    # "PASSWORD": "password",
    # "HOST": "localhost",
    # "PORT": "5432",
    # }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = (
    # 'oscar.apps.customer.auth_backends.EmailBackend',
    "django.contrib.auth.backends.ModelBackend",
)


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "/static_root/"
SASS_PROCESSOR_ENABLED = True
SASS_PROCESSOR_AUTO_INCLUDE = False
SASS_PROCESSOR_INCLUDE_FILE_PATTERN = r"^.+\.scss$"
# SASS_OUTPUT_STYLE = 'compact'

SASS_PRECISION = 10
SASS_ROOT = os.path.join(BASE_DIR, "assets")
SASS_PROCESSOR_ROOT = SASS_ROOT
STATIC_ROOT = os.path.join(BASE_DIR, "static_root")

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"), os.path.join(BASE_DIR, "assets"))

SASS_PROCESSOR_INCLUDE_DIRS = [
    os.path.join(BASE_DIR, "assets", "scss"),
    os.path.join(BASE_DIR, "node_modules"),
]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "sass_processor.finders.CssFinder",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


####################################
##  CKEDITOR CONFIGURATION ##
####################################

CKEDITOR_JQUERY_URL = "https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": [
            [
                "Undo",
                "Redo",
                "-",
                "Bold",
                "Italic",
                "Underline",
                "-",
                "Link",
                "Unlink",
                "Anchor",
                "-",
                "Format",
                "-",
                "Maximize",
                "-",
                "Table",
                "-",
                "Image",
                "-",
                "Source",
                "-",
                "NumberedList",
                "BulletedList",
            ],
            [
                "JustifyLeft",
                "JustifyCenter",
                "JustifyRight",
                "JustifyBlock",
                "-",
                "Font",
                "FontSize",
                "TextColor",
                "-",
                "Outdent",
                "Indent",
                "-",
                "HorizontalRule",
                "-",
                "Blockquote",
            ],
        ],
        "skin": "moono",
        "forcePasteAsPlainText": True,
        "format_tags": "p;h1;h2;h3;pre",
        "contentsCss": [
            "/static/css/ckeditor_init.css",
        ],
        "stylesSet": [
            {"name": "Строчный код", "element": "code"},
            {
                "name": "Скрыть для мобильных",
                "element": "span",
                "attributes": {"class": "hide_for_mobile"},
            },
            {
                "name": "Монолитный элемент",
                "element": "span",
                "attributes": {"style": "white-space: nowrap;"},
            },
            {
                "name": "Адаптивная таблица",
                "element": "div",
                "attributes": {"class": "table-responsive"},
            },
        ],
        "fontSize_sizes": "8/8px;9/9px;10/10px;11/11px;12/12px;13/13px;14/14px;15/15px;16/16px;17/17px;18/18px;19/19px;20/20px;"
        "21/21px;22/22px;23/23px;24/24px;25/25px;26/26px;27/27px;28/28px;36/36px;48/48px;72/72px;1/1px;",
    }
}


####################################
###  DJANGO-RESIZED CONFIGURATION ##
####################################
DJANGORESIZED_DEFAULT_SIZE = [1920, 1080]
DJANGORESIZED_DEFAULT_QUALITY = 75
DJANGORESIZED_DEFAULT_KEEP_META = True
DJANGORESIZED_DEFAULT_FORCE_FORMAT = "JPEG"
DJANGORESIZED_DEFAULT_FORMAT_EXTENSIONS = {"JPEG": ".jpg"}
DJANGORESIZED_DEFAULT_NORMALIZE_ROTATION = True


home = str(Path.home())
# import pdb; pdb.set_trace()
# with open(os.path.join('/', 'home', 'popov', 'send_mail_secret.json'), 'r') as f:
# with open(os.path.join(home, "send_mail_secret.json"), "r") as f:
#     json_email_settings = f.read()
#     email_settings = json.loads(json_email_settings)
#     EMAIL_HOST = email_settings["EMAIL_HOST"]
#     EMAIL_PORT = email_settings["EMAIL_PORT"]
#     EMAIL_HOST_USER = email_settings["EMAIL_HOST_USER"]
#     EMAIL_HOST_PASSWORD = email_settings["EMAIL_HOST_PASSWORD"]


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_SSL = True

TELEGRAM_BOT_API_KEY = "6120471530:AAFZo0JZTJ7wOo3sugkbi33LUfBvWMPyT9w"
TELEGRAM_PASSWORD_ADMIN = "12345678"

from .local_settings import *

if "installed_server_apps" in locals():
    INSTALLED_APPS += installed_server_apps

if "server_middleware" in locals():
    MIDDLEWARE += server_middleware
